### ISSUE TITLE
Dealing with Margin of Error Columns

### ISSUE THREAD

**Issue by jonmgeiger** [jonmgeiger/household-conditions#5]
For each measure in our dataset, we have a margin of error associated with that measure as a proportion.

**Comment by jonmgeiger** [comment]
Is there a way to convert between margin of error (with a given percent range) and *weight* of that data point, for something like a regression model? Defining the **range** as the range of the margin of error (e.g. 40%-70% is a 30% range), then the SE (standard error) would be range/2. 

Ideas: 
- (1/range) or (1/SE)
- 100 - range (or 50 - SE)

**Comment by jonmgeiger** [comment]
Next steps: getting an idea of how the ranges / standard errors are distributed, and how that relates to the amount of students in each school district. Is there a 1:1 correspondence between number of children in a school district and the standard error?

**Comment by noelgoodwin** [comment]
The Census Bureau has documentation of the methodology used by the ACS to calculate estimates and margin of errors.

[ACS Design and Methodology – Chapter 12: Variance Estimation](https://www2.census.gov/programs-surveys/acs/methodology/design_and_methodology/acs_design_methodology_ch12_2014.pdf) 
(See Section 12.3: Margin of Error and Confidence Interval)

[Documentation for the 2014-2018 Variance Replicate Estimates Tables](https://www2.census.gov/programs-surveys/acs/replicate_estimates/2018/documentation/5-year/2014-2018_Variance_Replicate_Tables_Documentation.pdf)  
(See page 8 about MOEs for Zero Counts and Percent Estimates of Zero or 100 Percent)

[Here](https://www.census.gov/programs-surveys/acs/data/variance-tables.2018.html) is more data, documentation, and table shells for 2018 regarding instructions on how to calculate margins of error for aggregated estimates, percentages, and ratios

**Comment by noelgoodwin** [comment]
https://www.census.gov/programs-surveys/acs/data/variance-tables.2018.html
There is some documentation at the bottom of the page that includes the k values and average weights based on location and population.
